# Generated by Django 2.2.5 on 2020-08-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200821_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='langauge',
            field=models.CharField(blank=True, choices=[('english', 'en'), ('korean', 'ko')], max_length=6),
        ),
    ]
